import Head from "next/head";
import React from "react";

function Preloader() {
  return (
    <>
      <Head>
        <title>Loading</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>  
    <div className="preloader">
      <div className="loader">
        <span />
        <span />
        <span />
        <span />
      </div>
    </div></>
  );
}

export default Preloader;
